### ISSUE TITLE
怎么配置环境变量呢？

### ISSUE THREAD

**Issue by vicky8989** [imfly/js2uml#3]
npm 安装后，提示无命令，js2uml 该怎么配置它的环境变量呢？

**Comment by imfly** [comment]
要先安装Node，保证`node -v`提示成功

**Comment by vicky8989** [comment]
![js2uml](https://user-images.githubusercontent.com/23472980/43383497-c4f98e86-940d-11e8-97b9-5047e3be8464.png)

运行出错呢？

**Comment by imfly** [comment]
win 下可能存在兼容问题，比如：用 .\uml\map.jpg 而不是 ./uml/map.jpg

**Comment by vicky8989** [comment]
Graphviz 已安装。nodeJs 6.14.3 。还是不行呢。
![image](https://user-images.githubusercontent.com/23472980/43384052-6090feb4-940f-11e8-84b0-a5e75da91324.png)

**Comment by vicky8989** [comment]
graphviz已安装，nodeJs v6.14.3，路径已换成  ./uml/map.png,还是报一样的错误呢。

**Comment by imfly** [comment]
应该是代码里有些npm不支持导致的，最近没时间修改了，你尝试自己修补一下即可
